language: python

script:
  # Run the python tests.
  - ./util/test_python.bash
  # Test that the docs actually build.
  - cd docs/ && make html

addons:
  apt:
    packages:
      - bc
      - tcsh
      - libgmp10
      - libgmp-dev
sudo: false
