language: python
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq bc tcsh
script:
  # Test the code snippets.
  #- ./util/test_all.bash
  - ./util/test_python.bash
  # Test that the docs actually build.
  - cd docs/ && make html
  # Run the py.test test-suite bla
  - pych --testing
